apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  GOOGLE_ANALYTICS_ID: {{ .Values.secrets.GOOGLE_ANALYTICS_ID | b64enc | quote }}
