version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.1.1

executors:
  builder:
    docker:
      - image: circleci/node:12-buster-browsers
    working_directory: ~/app

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/build_docker:
          name: build_docker
          image_name: "quay.io/hmpps/prison-services-feedback-and-support"
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          requires:
            - build_docker
          filters:
            branches:
              only: main

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit