version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.14

jobs:
  build:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Compile sass
          command: npm run compile-sass
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/build_docker:
          name: build_docker
          image_name: "quay.io/hmpps/prison-services-feedback-and-support"
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context:
            - hmpps-common-vars
          requires:
            - build_docker
          filters:
            branches:
              only: main
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - prison-services-feedback-and-support-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          context:
            - hmpps-common-vars
            - prison-services-feedback-and-support-prod
          slack_notification: true
          requires:
            - request-prod-approval


  security:
    triggers:
      - schedule:
          cron: "41 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit:
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "54 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
