---
# Values here are the same across all environments
generic-prometheus-alerts:
  targetApplication: prison-services-feedback-and-support

generic-service:
  replicaCount: 2

  nameOverride: prison-services-feedback-and-support

  image:
    repository: quay.io/hmpps/prison-services-feedback-and-support
    tag: app_version
    port: 3000

  ingress:
    enabled: true
    tlsSecretName: prison-services-feedback-and-support-cert

  namespace_secrets:
    prison-services-feedback-and-support:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"

  env:
    NODE_ENV: "production"
