# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/prison-services-feedback-and-support
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: support.hmpps.service.justice.gov.uk
  cert_secret: prison-services-feedback-and-support-cert
  path: /

env:
  NN_ENDPOINT_URL: https://digital.prison.service.justice.gov.uk/
  PRISON_STAFF_HUB_UI_URL: "https://digital.prison.service.justice.gov.uk/"
  OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth/
  ALLOCATION_MANAGER_ENDPOINT_URL: https://moic.service.justice.gov.uk/
  PATHFINDER_URL: https://pathfinder.service.justice.gov.uk/
