# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
generic-service:
  ingress:
    host: support-preprod.hmpps.service.justice.gov.uk

  env:
    NN_ENDPOINT_URL: https://digital-preprod.prison.service.justice.gov.uk/
    PRISON_STAFF_HUB_UI_URL: "https://digital-preprod.prison.service.justice.gov.uk/"
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/
    ALLOCATION_MANAGER_ENDPOINT_URL: https://allocation-manager-preprod.apps.live-1.cloud-platform.service.justice.gov.uk/
    PATHFINDER_UI_URL: https://preprod.pathfinder.service.justice.gov.uk/
    SOC_UI_URL: https://manage-soc-cases-preprod.hmpps.service.justice.gov.uk/

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev