# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/prison-services-feedback-and-support
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: support.hmpps.service.justice.gov.uk
  cert_secret: prison-services-feedback-and-support-cert
  path: /

env:
  NN_ENDPOINT_URL: https://digital.prison.service.justice.gov.uk/
  PRISON_STAFF_HUB_UI_URL: "https://digital.prison.service.justice.gov.uk/"
  OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth/
  ALLOCATION_MANAGER_ENDPOINT_URL: https://moic.service.justice.gov.uk/
  PATHFINDER_UI_URL: https://pathfinder.service.justice.gov.uk/

allowlist:
  office: "217.33.148.210/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  health-kick: "35.177.252.195/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  mojvpn: "81.134.202.29/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  sodexo-northumberland: "88.98.48.10/32"
  sodexo-northumberland2: "51.148.47.137/32"
  sodoxeo-forest-bank: "51.155.85.249/32"
  sodexo-peterborough: "51.155.55.241/32"
  serco: "217.22.14.0/24"
  ark-nps-hmcts-ttp1: "195.59.75.0/24"
  ark-nps-hmcts-ttp2: "194.33.192.0/25"
  ark-nps-hmcts-ttp3: "194.33.193.0/25"
  ark-nps-hmcts-ttp4: "194.33.196.0/25"
  ark-nps-hmcts-ttp5: "194.33.197.0/25"
  oakwood-1: "217.161.76.187/32"
  oakwood-2: "217.161.76.195/32"
  oakwood-3: "217.161.76.186/32"
  oakwood-4: "217.161.76.194/32"
  durham-tees-valley: "51.179.197.1/32"
  interservfls: "51.179.196.131/32"
  sodexo1: "80.86.46.16/32"
  sodexo2: "80.86.46.17/32"
  sodexo3: "80.86.46.18/32"
  sodexo4: "51.148.9.201"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  dxc_webproxy1: "195.92.38.20/32"
  dxc_webproxy2: "195.92.38.21/32"
  dxc_webproxy3: "195.92.38.22/32"
  dxc_webprox23: "195.92.38.23/32"
  moj-official-tgw-prod: "51.149.250.0/24"
  moj-official-tgw-preprod: "51.149.251.0/24"
  crc-rrp: "62.253.83.37/32"
  crc-pp-wwm: "5.153.255.210/32"
  moj-official-ark-c-expo-e: "51.149.249.0/29"
  moj-official-ark-c-vodafone: "194.33.248.0/29"
  moj-official-ark-f-vodafone: "194.33.249.0/29"
  moj-official-ark-f-expo-e: "51.149.249.32/29"
  met-police-talktalk-vpn-1: "212.139.143.66/32"
  met-police-talktalk-vpn-2: "212.74.97.221/32"
  police-1: "81.144.174.115/32"
  police-2: "81.144.241.238/32"
  police-3: "62.252.202.50/32"
  police-4: "80.194.71.110/32"
  police-5: "52.56.62.0/24"
  police-6: "80.193.134.32/32"
  police-7: "195.92.38.21/32"
  police-8: "80.193.128.200/32"
  police-9: "194.73.161.50/32"
  police-10: "165.225.81.49/32"
  police-11: "195.89.175.213/32"
  police-12: "195.89.175.229/32"
  police-13: "31.121.22.64/27"
  police-14: "82.16.19.192/27"
  police-west-york-1: "195.188.22.0/27"
  police-west-york-2: "195.188.22.128/27"
  police-west-york-3: "195.89.14.37"
  police-west-york-4: "195.27.188.37"
  police-south-york-public: "80.193.114.10"
  police-south-york-mossway: "51.231.157.126"
  police-south-york-atlas: "51.231.157.222"
  police-humberside-public: "80.100.176.162"
  police-humberside-priory: "51.231.157.226"

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
